services:
  refapi:
    image: refapi
    build:
      context: .
      dockerfile: src/RefApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=RefApiDb;Username=postgres;Password=root
      - OpenAIOptions__ApiKey=your-openai-api-key-here
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      - ref-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=RefApiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ref-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  ref-network:
    driver: bridge

volumes:
  postgres-data: